(beginning-of-buffer)
(search-forward "National Radio")
(forward-line -1)
(beginning-of-line)
(let ((beg (point))) 
(re-search-forward "SUBROUTINE\\|FUNCTION")
(beginning-of-line)
(delete-region beg (point)))
(insert-file "/sparc2/sde/doc/short.header")
(beginning-of-buffer)
(replace-regexp "^CA" "C")
(replace-regexp "^CD" "C")
(replace-regexp "^CE" "C")
(replace-regexp "^CS" "C")
(replace-regexp "^C Arguments:.*$" "C")
(beginning-of-buffer)
(re-search-forward "SUBROUTINE\\|FUNCTION")
(re-search-forward "^C .*$")
(beginning-of-line)
(forward-char)
(insert-file "/sparc2/sde/doc/D")
(save-buffers-kill-emacs 1)



