C
C	National Radio Astronomy Observatory, Socorro, NM 87801
C	Software Development Environment (SDE)
C++
C @(#)ipcprob.f	1.1    2/10/93
C
      SUBROUTINE IPCPROB (FRINGE, FRWIDTH, FRHEIGHT, NFRINGES, PHOTONS, 
     $     XLOC, YLOC,  NPHOTONS, PROB)
C
CD Given a set of fringe patterns, frame of photons return the prob(patterns)
C
C Given a set of fringe patterns and a frame of photons this routine will 
C  return the probability that the frame of photons was generated by each
C  of the fringe patterns.
C
C	FRINGE	REAL(FRWIDTH, FRHEIGHT, NFRINGES) Classical Fringe Patterns
C	FRWIDTH,FRHEIGHT INTEGER Size of the above array
C       NFRINGES INTEGER        Third Dimension of above array
C       PHOTONS REAL(NPHOTONS)  Number of Photons in each of pixel
C       XLOC    REAL(NPHOTONS)  X Location of each Photon           
C       YLOC    REAL(NPHOTONS)  Y Location of each Photon   
C       NPHOTONS INTEGER        Size of above arrays  
C       PROB    REAL (NFRINGES) Returned probability for each frame
C
C Audit trail:
C	Original version: Audit trail comments go on this line
C	and successive lines
C				R.G. Marson	Oct 1 1992
C       Converted to real PDF's
C                               R.G. Marson     Dec 29 1992

C
C-----------------------------------------------------------------------
C
#include		"stdinc.h"
C
C Input Variables
C
      INTEGER           FRWIDTH, FRHEIGHT, NPHOTONS, NFRINGES
      REAL              PROB(NFRINGES)
      REAL              FRINGE(FRWIDTH, FRHEIGHT, NFRINGES)
      REAL              XLOC(NPHOTONS), YLOC(NPHOTONS)
      REAL              PHOTONS(NPHOTONS)
C
C Parameter Definitions
C
      CHARACTER*(*)	ROUTINE
      PARAMETER		(ROUTINE = 'IPCPROB')
C
C Local Variables
C
      INTEGER I
C
C=======================================================================
C
C If an error on input then exit immediately
C
      IF (ERROR) GO TO 999
C
C Begin gode here
C
      DO I = 1, NFRINGES
         CALL IPCPROBS(FRINGE(1,1,I), FRWIDTH-1,  FRHEIGHT-1,
     $        PHOTONS, XLOC, YLOC, NPHOTONS, PROB(I))
      END DO
C
C Can jump to here if an error found
C
  990 IF (ERROR) THEN
         CALL ERRTRACE (ROUTINE)
      END IF
C
  999 CONTINUE
      END
