C
C	National Radio Astronomy Observatory, Socorro, NM 87801
C	Software Development Environment (SDE)
C++
C @(#)ipcprobs.f	1.1    2/10/93
C
      SUBROUTINE IPCPROBS (FRINGE, FRWIDTH, FRHEIGHT, PHOTONS, 
     $     XLOC, YLOC, NPHOTONS, PROB)
C
CD Give a fringe pattern and a frame of photons return the prob. of the pattern
C
C Given a fringe pattern and a frame of photons this routine will return
C  the probability that the frame of photons was generated by the specified
C  fringe pattern
C
C	FRINGE	REAL(0:FRWIDTH, 0:FRHEIGHT) Classical Fringe Pattern
C	FRWIDTH, FRHEIGHT INTEGER Size of the above array
C       PHOTONS REAL(NPHOTONS)  Number of Photons in each of pixel
C       XLOC    REAL(NPHOTONS)  X Location of each Photon           
C       YLOC    REAL(NPHOTONS)  Y Location of each Photon   
C       NPHOTONS INTEGER        Size of above arrays  
C       PROB    REAL            Returned probability
C
C Audit trail:
C	Original version: Audit trail comments go on this line
C	and successive lines
C				R.G. Marson	Oct 1 1992
C	Changed to using LOG(Prob) to avoid overflow problems
C				R.G. Marson	Oct 26 1992
C       Converted to real PDF's and moved clipping to SDEMAIN
C                               R.G. Marson     Dec 29 1992
C
C-----------------------------------------------------------------------
C
#include		"stdinc.h"
C
C Input Variables
C
      INTEGER           FRWIDTH, FRHEIGHT, NPHOTONS
      REAL              PROB
      REAL              FRINGE(0:FRWIDTH, 0:FRHEIGHT)
      REAL              XLOC(NPHOTONS), YLOC(NPHOTONS)
      REAL              PHOTONS(NPHOTONS)
C
C Parameter Definitions
C
      CHARACTER*(*)	ROUTINE
      PARAMETER		(ROUTINE = 'IPCPROBS')
C
C Local Variables
C
      INTEGER I
C
C=======================================================================
C
C If an error on input then exit immediately
C
      IF (ERROR) GO TO 999
C
C Begin gode here
C
      PROB = 0.0
      DO I = 1, NPHOTONS
         IF (PHOTONS(I).EQ.1) THEN
            PROB = PROB + FRINGE(XLOC(I), YLOC(I))
         ELSE
            PROB = PROB + FRINGE(XLOC(I), YLOC(I)) + LOG(PHOTONS(I))
         END IF
      END DO
C
C Can jump to here if an error found
C
  999 CONTINUE
      END
