# LaTeX2HTML 95 (Thu Jan 19 1995)
# Associate image original text (scrambled) with physical files.

$key = q/{tabbing}<<161>>ttOUTNAME<<161>>=<<162>>ttCHARACTER*(*)<<162>>=Nameofentryindatabasekill<<163>>ttNAME<<163>>><<164>>ttCHARACTER*(*)<<164>>>Nameofentryindatabase<<165>>ttINNAME<<165>>><<166>>ttCHARACTER*(*)<<166>>>Nameofentryindatabase<<167>>ttOUTNAME<<167>>><<168>>ttCHARACTER*(*)<<168>>>Nameofentryindatabase<<169>>ttINFILE<<169>>><<170>>ttCHARACTER*(*)<<170>>>Nameofexternalinputfile<<171>>ttOUTFILE<<171>>><<172>>ttCHARACTER*(*)<<172>>>Nameofexternaloutputfile<<173>>ttITEM<<173>>><<174>>ttCHARACTER*(*)<<174>>>Nameofitemindatabaseentry<<175>>ttVALUE<<175>>><<176>>tt<<176>>>Arrayofvaluesofitem<<177>>ttNVALS<<177>>><<178>>ttINTEGER<<178>>>Numberofvalues<<179>>ttADD<<179>>><<180>>ttINTEGER<<180>>>Addressofvaluesin<<181>>ttMEM?<<181>>{tabbing}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_29564_tabbing160.xbm">'; 
$key = q/{tabbing}<<413>>ttERRNTFND..........<<413>>='Requesteditemnotfound'kill<<414>>ttERRFATAL<<414>>>'Fatalerror'<<415>>ttERRBDARG<<415>>>'Badsubroutineargument'<<416>>ttERRNOMEM<<416>>>'Nomemoryavailable'<<417>>ttERRNTFND<<417>>>'Requesteditemnotfound'<<418>>ttERRLOGIC<<418>>>'Programlogicerror'<<419>>ttERRNOSLT<<419>>>'Noslotavailable'<<420>>ttERRWRGTP<<420>>>'Itemisofwrongtype'<<421>>ttERRTRUNC<<421>>>'Resulttruncated'<<422>>ttERRBADID<<422>>>'Badidentifiersupplied'<<423>>ttERRDB<<423>>>'Internaldatabaseerror'<<424>>ttERRINPUT<<424>>>'Inputreaderror'<<425>>ttERROUTPT<<425>>>'Outputwriteerror'<<426>>ttERROPEN<<426>>>'Fileopenerror'<<427>>ttERRCLOSE<<427>>>'Filecloseerror'{tabbing}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_29564_tabbing412.xbm">'; 
$key = q/{tabbing}<<267>>ttHANDLE....<<267>>=<<268>>ttCHARACTER*(*)....<<268>>=Handlebywhichthisiostreamisknownkill<<269>>ttHANDLE<<269>>><<270>>ttCHARACTER*(*)<<270>>>Handlebywhichthisiostreamisknown<<271>>ttFILE<<271>>><<272>>ttCHARACTER*(*)<<272>>>Nameofexternalfile:canincludelogicalnames<<273>>ttLINE<<273>>><<274>>ttCHARACTER*(*)<<274>>>Lineforinputoroutput{tabbing}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_29564_tabbing266.xbm">'; 
$key = q/{tabbing}libraryconvexobject............=......copiesofobjectmoduleskillbin>executablesbinshadows>...shadowsofactualtasksbinibm6000>...executablesforibm6000binsparc>...executablesforSPARCmachinesbinunix>...scripts(allinBourneshell)data>Dataareadoc>Variousdocumentationhosts>Host-specificdirectoriesinf>Informationfilesfortaskslibrary>Librarieslibraryibm6000>...foribm6000libraryibm6000object>......copiesofobjectmoduleslibrarysparc>...forSPARClibrarysparcobject>......copiesofobjectmoduleslocal>Scriptsformidnightjobs,etcscratch>Scratchareasdeini>Bourne-orKorn-shellinitializationfilesdeini.csh>C-shellinitializationfilesource>Sourcecodesourcearr>Arraylevelroutinessourcecal>Calibrationroutinessourcecrd>Coordinatemanipulationssourcefft>FFTroutinessourcefil>Filesystemaccesssourcefts>FITSreadersandwriterssourcegrd>Griddingroutinessourcehed>Headermanipulationsourcehis>Historysystemsourceimg>Imagelevelroutinessourceinclude>Includefilessourcemain>mainsubroutinessourcemem>MaximumEntropyroutinessourcemod>Modelmanipulationsourcepix>Pixellevelroutinessourcesim>Simulationroutinessourcestart>MainsubroutineSDEMAINsourcetask>Taskssourcetaskarchive>OnceandFuturetaskssourceutl>Utilityroutinessourcevis>Visibilitymanipulationtest>Testdataandresultstools>VarioustoolsincludingMicroEmacseditor>forunfrilysystems,fortranlint,and>tvstuffforibm6000andsparcsystemsvar>Siteandmachinedepentscripts{tabbing}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_29564_tabbing406.xbm">'; 
$key = q/{tabbing}Operatingsystem:....=OS_BSD..............=OS_BSD.............=DOS................=SYSV........=killOperatingsystem:>OS_BSD>OS_SYSVMachine:>MACH_C1>MACH_C2>MACH_SUN3>MACH_SPARC>MACH_IBM6000>MACH_CRAY2Compiler:>COMP_CONVEX>COMP_SUN>COMP_IBM>COMP_CRAY{tabbing}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_29564_tabbing385.xbm">'; 
$key = q/{tabbing}<<197>>ttROUTINE....<<197>>=<<198>>ttCHARACTER*(*)....<<198>>=Nameoftheroutineinwhichanerroroccurredkill<<199>>ttREASON<<199>>><<200>>ttCHARACTER*(*)<<200>>>Reasonforerror:usuallyfromthestandardlist<<201>>ttROUTINE<<201>>><<202>>ttCHARACTER*(*)<<202>>>Nameoftheroutineinwhichanerroroccurred<<203>>ttTEXT<<203>>><<204>>ttCHARACTER*(*)<<204>>>Furtherexplanatorytext{tabbing}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_29564_tabbing196.xbm">'; 
$key = q/{tabbing}Includefilewithcompiletime....=SYSVER........=sdesourceincludesysver.h.....killTherootdirectory>SDEROOT>sdeLogfilefor<<476>>sfSDE<<476>>tasks>SDELOG>Scratcharea>SDESCR>sdescratchThresholdforscratchfiles>SDEMEM>8Machinetype>MACHINE>c1Placewherebinariesarekept>SDEBIN>sdebinc1Areafortestdata>D0>sdedataScratchdiskarea>T1>.Includefilewithcompiletime>SYSVER>sdesourceincludesysver.hLibraryofroutines>SDELIB>sdelibraryc1Areaforinffiles>SDEINF>sdeinfAreaforthismachine>SDEHOST>sdehostsyuccaNameoftvfile>SDETV>sdehoststecatetvfile{tabbing}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_29564_tabbing430.xbm">'; 
$key = q/{tabbing}Includefilewithcompiletime....=SYSVER........=sdesourceincludesysver.h.....killTherootdirectory>SDEROOT>sdeLogfilefor<<477>>sfSDE<<477>>tasks>SDELOG>Scratcharea>SDESCR>sdescratchThresholdforscratchfiles>SDEMEM>8Machinetype>MACHINE>c1Placewherebinariesarekept>SDEBIN>sdebinc1Areafortestdata>D0>sdedataScratchdiskarea>T1>.Includefilewithcompiletime>SYSVER>sdesourceincludesysver.hLibraryofroutines>SDELIB>sdelibraryc1Areaforinffiles>SDEINF>sdeinfAreaforthismachine>SDEHOST>sdehostsyuccaNameoftvfile>SDETV>sdehoststecatetvfile{tabbing}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_29954_tabbing430.xbm">'; 

1;

