/*
 * DO NOT EDIT -- generated by the Makefile
 */

/* the default :-separated search path */
#ifndef DEFAULTCALCPATH
#define DEFAULTCALCPATH ".:./lib:~/lib:/zia/u/sde/tools/calc/lib:/zia/u/sde/tools/calc/installed/lib"
#endif /* DEFAULTCALCPATH */

/* the default :-separated startup file list */
#ifndef DEFAULTCALCRC
#define DEFAULTCALCRC "/zia/u/sde/tools/calc/installed/lib/startup:~/.calcrc"
#endif /* DEFAULTCALCRC */

/* the location of the help directory */
#ifndef HELPDIR
#define HELPDIR "/zia/u/sde/tools/calc/help"
#endif /* HELPDIR */

/* the default pager to use */
#ifndef DEFAULTCALCPAGER
#define DEFAULTCALCPAGER "more"
#endif /* DEFAULTCALCPAGER */
